baseURL = "https://sylantiev.com/"
languageCode = "en-us"
title = "Sylantiev"

[params]
  font = "Inter"
  author = "Dmytro Sylantiev"
  description = "Dmytro Sylantiev"

[markup]
  # defaultMarkdownHandler = "goldmark"
  # [markup.goldmark]
  #   [markup.goldmark.extensions]
  #     typographer = true
  [markup.goldmark.renderer]
    unsafe = true

# theme = 'ananke'
[permalinks]
  archive = "/archive/:slug/"
  work = "/work/:slug/"
  lab = "/lab/:slug/"


